version: '3.8'

services:
  # Сервис Redis (Канальный слой для сокетов)
  redis:
    image: redis:7-alpine
    container_name: chat_redis
    ports:
      - "6379:6379"
    

  # Сервис нашего Django приложения
  web:
    build: .
    container_name: chat_web
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CHANNELS_DOCKER=true
    depends_on:
      - redis
    env_file:
      - .env